language: python
sudo: required
services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.0
  global:
    - secure: gyswLhR/pot1QoagdIikiWLolR9MfJI0yRSbeKAIK22txZNZs6sauNHBYmBgt8LV+c6j1aZbjmJn6mt6CKxJ+JZToIwk+aH4U/Ph7wudajSAK7x0nOa/aV1ARlzbiZ1d8m9Wv4VxFzEUHVD8TgL/P530UnD/qGj5seASaVISRbr1gufRrAWGKdn7zHfS32rrQOde1ONBZaW7DUcVA0kbtpgc3Y/pWbRAZHcYH2h6tUJb/Q9MLrXEVxXsARh73KEEL8QdKWk6dnWeHX5h6x4R4baRSPB5usM+0uGtmdVcUbTTkcJaCQR5v1eXjW9ghfIH1inWslIFyuO6hs9bypesOjdPkVJx1vCMT+jcPqqmYSAC3t5yRxAGMGH7qvSbHoGq7Wstx3v7ag1GVugIjhM1nJ3oZymIy5YwJlNNMdoeJrvSghirP+3QjuqwNMR7Onwd+Y/672NwdGA5l63bsGgX8PVtoXYwoSh9PQPbvtyoVPVA1ia6/7u1pl0g4FpxLbmaOkkkSNz0UIywlM/Cls82dH1qbv5BHwQxOkF3REtte/6pSlZsK055i0kX3xnruP2f9gbalGRKQRoT7l9XaLdu0XALAOnh1yvP0etPk/07cxUSRRtWUjVxJ0tM/DWTQcupRJs+oT+Ej32LFlosuFOlniprqpUk0Yhp5Re2fOfYN9A= # DOCKER_USER
    - secure: IDLg5bFAwIXLfonDWuNSoCMgC2RLvkt2ERoriueEAJrXSoelGs2XW1axqKVIYXEyW0iRygfKy+wxv2Rzb3HhMu84yPfOyUgyLSgx9Zx9M0wYXcevs2dCK+r1HGiVp823JlB07sSRap1C4O2Ry2YdgpIbwartYwPdRr0fYevj6p54IpjAmc3TYuN80yZZXg/gzFNEXZ/n7PG0KYPDALrow+at3uONU1wq1WMwuO+doenW9iYOS8n38IQ6fxcw09z1clt5CLZYC6TIwlYUpEr4e05Bs5rEi3z3omaaudmA4ImXPdCZ5/y8p78qna/4H4jcc1jl5rp2FvYVBxdE8VA2lSdCO55qAV89To9PJ4clTilxHUS3TXEhnLSPtBvKHWZGSUquoYjYuewS7aoLUQ/8KcBgnFCQ6QmZqmwPGEp88PI/VMqh1LUkXKi5Fg2+fx6Dn36xy9v/YpUjUB/Ki5sR7ZEyZXjTuFa/5X5sWgkYVPu15W3DnB1gxEO65llB8oBMVaQCR3gI8eLiRAMXw8xK4/GI8E6/1I/3iSfUMcMkXxVNPwgZ4HF7ELHXYYRoKb1cRowuVMAvik+PPs2QoHkIebGIK8itTMaMbKWzw76Gzpp4y/L8Y3qE1oZRWbN5x1IlyKfRNHugbUG8RZXq/ld1Egfgn8h29zGL+PybqbsO5uo= # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login --username=$DOCKER_USER --password=$DOCKER_PASS
  - export REPO=ga4gh/cgtd
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

branches:
  - master
  - no_init_bad_port

python:
  - '2.7'

install:
  - pip install pycodestyle
  - pip install flake8
script:
  - pycodestyle --max-line-length=150 .
  - make ipfs
  - sleep 5 # Wait for ipfs docker container init
  - make reset
  - make build
  - make run
  - make test
notifications:
  email: false
  slack:
    secure: DmhRJVIAOfdPROAYg208v/A2pFyov5YUUD4bYXZK0bQij9wjSVgxVC6SXF9KM4KW96ekIgsy51H1pDUO0XhZCmRZ3/sQm5xleuARgjwuk0sp7+F4w0EnZ0J8UsyyFOTGwHRL2G5/msxUcajlvOGquHmJtugy7AGCMwsBzu5ww3ObPvgvVumd+ZprRX5w4TJPxcSEXu9MQCUXI6fqTt6/lu8XqoQEMFQEdQcUOtAehS2To3jHNPwwkDlD2FQGR36WjIXgzPyYnd+COVVgJn15Or/DZ85+8nmQQszb/IQxsdvf8+DGtmvJxuC58dJjLSFBupCIwfUFLlfVHJDdb2JwuG2RSmizntdYR1sm+HR0eBtLx8ikNanPjlNSheWAvbqOWDnldHgbSzm5Nw0TWDzw4/61beSsvt0w6lP4ac4n6tvMYHiurpKHax8HawHMPZ2yoWtV6y/G8cmVKF67pya4DZOtiWiFiXTetXUhSPXc9Ox/SWZmnEVSbR8AxPEf0D7uNDMeBkOvvwJqHU+73pmola301BcDnnIlJye/00wOBmf+7nGzEgsjd1oTogPC0I9Xn910RvCTXzDCCROKYZZjLy168hxxhDXdAUT36U4CHaXma1TrEn1ehV6dCZUbwmXyap9/bJF4+y3SO+jKHo8dNfluCliubaJgce0ktxFAA/M=
