language: python

sudo: required

services:
  - docker

python:
  - '2.7'

install:
  - pip install pycodestyle
  - pip install flake8

script:
  - pycodestyle --max-line-length=150 .
  - make build
  - make up
  - sleep 5 # Wait for ipfs docker container init
  - make reset
  - make test
