version: '2'

volumes:
  ipfs:

services:
  ipfs:
    image: ipfs/go-ipfs:v0.4.15
    volumes:
      - ipfs:/data/ipfs
    ports:
      - "8080:8080"
      - "4001:4001"

  cgtd:
    image: cancergenetrust/cgtd:release
    environment:
      DOMAIN:
    ports:
      - "80:5000"
    links:
      - ipfs
